version: '3.7'
services:
  mongodb:
    image: mongo
    restart: always
  node-backend:
    image: node
    restart: always
    working_dir: /app
    depends_on:
      - mongodb
    environment: 
      - MONGODB_URI=mongodb://mongodb:27017/cpmanager
