version: '3.7'
services:
  node-backend:
    command: [sh, -ce, "yarn dev"]
    ports:
      - 5000:5000
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment: 
      - NODE_ENV=development

