version: '3.7'
services:
    node-backend:
      build: ./backend
      environment: 
        - NODE_ENV=production
      ports:
        - 5000:5000
    frontend:
      build: ./frontend
      environment: 
        - NODE_ENV=production
      ports:
        - 80:80

